services:
  winebox64-gaming:
    build: .
    container_name: winebox64-gaming
    stdin_open: true
    tty: true
    # Add privileged mode to remove kernel-level restrictions
    privileged: true
    # Share the host's process ID namespace, helps with some drivers
    pid: "host"
    ipc: "host"
    # Use host networking to share network and network devices
    network_mode: "host"
    volumes:
        - /mnt/shared:/mnt/shared:rw
        - wine_prefix:/home/gamer/.wine64
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - /usr/lib/aarch64-linux-gnu/libvulkan_gfxstream.so:/usr/lib/aarch64-linux-gnu/libvulkan_gfxstream.so:ro
        - /dev:/dev:rw
    environment:
      - MESA_LOADER_DRIVER_OVERRIDE=zink
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/gfxstream_vk_icd.json
      - MESA_VK_WSI_DEBUG=sw,linear
      - XWAYLAND_NO_GLAMOR=1
      - LIBGL_KOPPER_DRI2=1
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=/tmp/.X11-unix
    command: ["bash"]

volumes:
  wine_prefix: