services:
  winebox64-gaming:
    build: .
    container_name: winebox64-gaming
    stdin_open: true
    tty: true
    # Privileged mode is required for the container to modify its own iptables rules.
    privileged: true
    # Share the host's process ID namespace, helps with some drivers
    pid: "host"
    ipc: "host"
    # Use host networking to share network and network devices
    network_mode: "host"
    
    volumes:
        - /mnt/shared:/mnt/shared:rw
        - wine_prefix:/home/gamer/.persist:rw
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - /usr/lib/aarch64-linux-gnu/libvulkan_gfxstream.so:/usr/lib/aarch64-linux-gnu/libvulkan_gfxstream.so:ro # Vulkan gfxstream
        - /usr/lib/aarch64-linux-gnu/libGL.so.1:/usr/lib/aarch64-linux-gnu/libGL.so.1:ro # OpenGL Zink
        - /dev:/dev:rw
    environment:
        - MESA_LOADER_DRIVER_OVERRIDE=zink
        - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/gfxstream_vk_icd.json
        - MESA_VK_WSI_DEBUG=sw,linear
        - XWAYLAND_NO_GLAMOR=1
        - LIBGL_KOPPER_DRI2=1
        - DISPLAY=${DISPLAY:-:0}
        - XAUTHORITY=/tmp/.X11-unix
        - BOX64_DYNAREC_BIGBLOCK=1
        - BOX64_DYNAREC_STRONGMEM=1
        - BOX64_DYNAREC_FASTNAN=1
        - BOX64_DYNAREC_FASTROUND=1
        - BOX64_DYNAREC_ALIGNED_ATOMICS=1
        - BOX64_UNITYPLAYER=1
        - BOX64_SYNC_ROUNDING=1
        - BOX64_DYNAREC_DIRTY=1
        - MESA_EXTENSION_OVERRIDE="-GL_ARB_framebuffer_sRGB -GL_EXT_texture_sRGB"
        - SDL_JOYSTICK_DEVICE=/dev/input/event4
      
    command: >
      /bin/bash -c "
      exec bash
      "

volumes:
  wine_prefix:

